# Pyproject TOML configuration file

# Black settings
# Doco:  https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html
[tool.black]
line-length = 120
exclude = "(venv|fusion-identity-data|pg-data|migrations)"

# Mypy settings:
# Doco: https://mypy.readthedocs.io/en/stable/config_file.html#the-mypy-configuration-file
[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
strict = true
show_error_codes = true
disallow_subclassing_any = false 
warn_unused_ignores = false
# lib is excluded until it's addressed at it's own repo level
exclude = "(venv)"

# Pydocstyle settings
# Doco: http://www.pydocstyle.org/en/stable/snippets/config.html
[tool.pydocstyle]
convention = "google"
# Skip the following folders
match_dir = '^(?!(venv)).*'

# Isort settings
# Doco: https://pycqa.github.io/isort/
[tool.isort]
# set the settings that are recommended with black
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = true
balanced_wrapping = true
use_parentheses = true
ensure_newline_before_comments = true 
# Skip the following folders
skip = [".gitignore", ".dockerignore", "venv"]
